# Generated by Django 4.0.4 on 2022-05-31 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_client_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date',
        ),
    ]
